### PR TITLE
Remove initiator

### PR DESCRIPTION
**Pull request by StephenCoady**
@PhilipGough @luigizuccarelli  please review

### CODE REVIEW

**Comment by PhilipGough** [comment]
Retest this please

**Comment by PhilipGough** [comment]
Retest this please

**Comment by StephenCoady** [comment]
Retest this please

**Comment by grdryn** [comment]
Retest this please.

**Comment by grdryn** [comment]
Retest this please.

**Comment by grdryn** [comment]
Retest this please.

**Comment by grdryn** [comment]
Retest this please.

**Pull request merged**
