### PR TITLE
Merge latest master from upstream to get 3.2 image, & apply our customizations

### PR DESCRIPTION
**Pull request by grdryn**
Upstream is https://github.com/sclorg/mongodb-container/

The commits from myself are really all that's expected to be reviewed here.

### CODE REVIEW

**Comment by grdryn** [comment]
@luigizuccarelli this should work for you. Would you like to review?

@rhcarvalho This could benefit from your eyes also, if you have some time! :)

**Comment by luigizuccarelli** [comment]
@grdryn Ok having a look now (only the 3.2 stuff)

**Comment by grdryn** [comment]
Retest this please. (I've added the 3.2 image to be built by jenkins)

**Comment by luigizuccarelli** [comment]
@grdryn - Built the image locally using rhel7

Removing intermediate container 88404f493b48
Successfully built f7d6723945f6

Next step is to actually create an MBaaS on node :)

**Comment by luigizuccarelli** [comment]
@grdryn Can you have a look at the permissions - I'm getting this error

```bash
 I ACCESS   [conn1] note: no users configured in admin.system.users, allowing localhost access
=> MongoDB daemon is up
2016-06-09T14:01:26.860-0400 I ACCESS   [conn17] SCRAM-SHA-1 authentication failed for u-mbaas on fh-mbaas from client 10.1.0.16 ; UserNotFound: Could not find user u-mbaas@fh-mbaas
```

**Comment by grdryn** [comment]
@luigizuccarelli can you tell me the steps you performed to get to that state?

**Comment by luigizuccarelli** [comment]
@grdryn I got the 1 node template working now. I updated the SERVICE to "mongodb".
I noticed also that we have run-mongod as a binary rather than run-mongod.sh - also changed this in the template. Looking good

**Comment by luigizuccarelli** [comment]
@grdryn reviewed

**Pull request merged**
