### PR TITLE
add rh-mongodb32-mongo-tools rhscl to mongodb 3.2 containers

### PR DESCRIPTION
**Pull request by philbrookes**
Required for mongodump executable.

### CODE REVIEW

**Comment by fh-automatron** [comment]
### Pull Request Quality Guidelines

As we continue to focus on quality, here are a few things to keep in mind:

* The code changes conform to the contributing & code style guides for this component (if they exist)
* A component owner should review your change (we've tagged these above)
* Automated testing has been added or updated for this change (e.g. UART, Unit/Acceptance tests)
* If updating server component this PR should be deployed to a grid somewhere (via `fhcap-cli`) - please provide a link to this
* Ensure JIRA is up to date before & after merge (e.g. deployment notes, tester notes, release notes, fix version)
* Any SonarQube issues should be addressed where applicable (use your own judgement)

Please ping a component owner (see `fh contrib`) when your builds are complete, changes are deployed and you're ready for a review.
Fhcap PR will be generated automatically.
To deploy your changes to a cluster place comment in this PR with pattern [x][y] where x=deploy and y=clustername you wish to deploy. 
You can also deploy your change manually using fhcap-cli

**Comment by philbrookes** [comment]
Retest this please.

**Comment by philbrookes** [comment]
Retest this please.

**Comment by jessesarn** [comment]
retest this please

**Comment by jessesarn** [comment]
retest this please

**Comment by jessesarn** [comment]
retest this please

**Comment by jessesarn** [comment]
retest this please

**Comment by jessesarn** [comment]
Finally got it to build... wasn't easy.  Added a temporary 512MB swapfile which was enough to let it complete.  It only used up 107MB of the swap, so going to shrink it to 256MB and set up /etc/fstab to mount it so at least we can redo builds in the future without all the crap.

**Comment by jessesarn** [comment]
@philbrookes all better.  I don't think we'll have the usual 50 rebases required to move forward here, so go ahead and merge after you double check me.  This goes with [https://github.com/fheng/fh-openshift-templates/pull/853]

**Comment by rhcarvalho** [comment]
This has also landed upstream, https://github.com/sclorg/mongodb-container/pull/187 :tada:

**Pull request merged**
